delete from Files;
delete from Librarian;
delete from ManySubjects;
delete from Publisher;
delete from Student;
delete from Subjects;
delete from User;
delete from BorrowedBooks;
delete from AddedBooks;
